matrix:
  include:
    - language: ruby
      rvm: 2.2
      before_script:
        - gem install awesome_bot
      script:
        - ./terminals_are_sexy.sh
        - awesome_bot readme.md --allow-dupe --allow-redirect

    - language: python
      python: 3.6.7
      install:
        - pip install mkdocs mkdocs-cinder
        - wget https://raw.githubusercontent.com/k4m4/terminals-are-sexy/master/readme.md
        - cat readme.md | sed -e '1,2d' -e '6,10d' > docs/index.md
        - sed -i '5i<script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?serve=CE7DEK3E&placement=terminalsaresexy" id="_carbonads_js"></script>' docs/index.md
        - rm -rf readme.md
      script:
        - mkdocs build --verbose --clean --strict
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: site
        on:
          branch: master